# Test linear regression

In [1]:
import numpy as np
np.set_printoptions(precision=4)

data is a nxm array with
* n := number of data point
* m := variables as id/b0/b1/b2/.../bn

In [20]:
data = np.array([[0, 1, 1, 1, 1, 1], [1, 1, -1, -1, -1, -1], [2, 1, 2, 2, 2, 2]])

In [21]:
print(data)

[[ 0  1  1  1  1  1]
 [ 1  1 -1 -1 -1 -1]
 [ 2  1  2  2  2  2]]


In [52]:
def fit_linear_regression(x, y, lr=0.1, n_iter=10):
    print("x", np.shape(x))
    print(x)
    print("y", np.shape(y))
    print(y)
    print()
    
    # retrieve parameters
    n_variable = np.shape(x)[-1]
    n_points = np.shape(x)[0]
    print("n_variable", n_variable)
    # declare a weight for each variable
    weights = np.zeros(n_variable)
    # weights = np.array([2.0, 5.0])
    print("weights", np.shape(weights))
    print(weights)
    print()
    
    for i in range(n_iter):
        # compute predictions y^
        y_hat = np.dot(x, weights)

        # compute errors 
        diffs = np.expand_dims(y - y_hat, 0)
        SSE = np.sum(np.power(diffs, 2))
        print("{} SSE:{:0.4f}, MSE:{:0.4f}".format(i, SSE, np.sqrt(SSE)))

        # compute gradient for each points
        grads = np.squeeze(2 * np.dot(diffs, x))

        # update parameters
        weights += lr / n_points * grads
     
    print()
    print("weights")
    print(weights)
    

In [54]:
fit_linear_regression(data[:, 1:3], data[:, -1], lr=0.1, n_iter=6)

x (3, 2)
[[ 1  1]
 [ 1 -1]
 [ 1  2]]
y (3,)
[ 1 -1  2]

n_variable 2
weights (2,)
[0. 0.]

[0. 0. 0.]
[[ 1. -1.  2.]]
0 SSE:6.0000, MSE:2.4495
[ 4. 12.]
[0.1333 0.4   ]

[ 0.5333 -0.2667  0.9333]
[[ 0.4667 -0.7333  1.0667]]
1 SSE:1.8933, MSE:1.3760
[1.6    6.6667]
[0.1867 0.6222]

[ 0.8089 -0.4356  1.4311]
[[ 0.1911 -0.5644  0.5689]]
2 SSE:0.6788, MSE:0.8239
[0.3911 3.7867]
[0.1997 0.7484]

[ 0.9481 -0.5487  1.6966]
[[ 0.0519 -0.4513  0.3034]]
3 SSE:0.2984, MSE:0.5462
[-0.192   2.2199]
[0.1933 0.8224]

[ 1.0157 -0.6291  1.8382]
[[-0.0157 -0.3709  0.1618]]
4 SSE:0.1640, MSE:0.4049
[-0.4496  1.3575]
[0.1783 0.8677]

[ 1.046  -0.6894  1.9137]
[[-0.046  -0.3106  0.0863]]
5 SSE:0.1061, MSE:0.3257
[-0.5407  0.8745]
[0.1603 0.8968]


weights
[0.1603 0.8968]
